### ISSUE TITLE
Install/build of ember-cli-normalizr-shim fail

### ISSUE THREAD

**Issue by dbashford** [ember-redux/ember-cli-normalizr-shim#1]
When normalizr updated to 3.3, it altered what got distributed to NPM such that the following fails when running the build.

`Cannot find module 'normalizr/dist/src/index.js'`

`dist/src/index.js` is no longer there.

`normalizr` is allowed to float in the `package.json`: `"normalizr": "^3.2.2",`. I fixed it to `3.2.2` in our build to keep things chugging along. I forked and headed down the path of fixing things here, but ended up in a library refresh rabbit hole and I'm too heads down in build stuff to dig into that.

Ticket to track!

**Comment by toranb** [comment]
@dbashford  great catch! Some good news w/ this v3.3.0 release -we shouldn't need this shim anymore! I made note of this just now in the README for anyone who might follow. Because the `normalizr` library offers a legit AMD build you can use a simple app.import instead!

```js
app.import('node_modules/normalizr/dist/normalizr.amd.js', {
  using: [{transformation: 'amd', as: 'normalizr'}]
});
```
